= Front Controller
:toc:

link:00-intro.adoc[<< Введение].

https://ru.wikipedia.org/wiki/%D0%95%D0%B4%D0%B8%D0%BD%D0%B0%D1%8F_%D1%82%D0%BE%D1%87%D0%BA%D0%B0_%D0%B2%D1%85%D0%BE%D0%B4%D0%B0_(%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD_%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F)[Front Controller (Фронт контроллер)] - это единая точка входа для вашего приложения.

Для начала, давайте создадим директорию для нашего проекта. Нам также понадобится определить единую точку входа, которая будет обрабатывать все запросы. Для этого необходимо создать файл `index.php`.

Часть разработчиков оставляют `index.php` в корневой папке проекта, такой подход также используется в некоторых фреймворках. Но так делать не стоит, позвольте мне объяснить почему.

Поскольку `index.php` является отправной точкой приложения, данный файл должен находиться в каталоге веб-сервера. Веб-сервер, в свою очередь, имеет доступ ко всем подкаталогам. Поэтому, данные, находящиеся на одном уровне с `index.php` становятся доступны для веб-сервера.

Конечно же, если вы настроите правильно конфигурацию сервера и ограничите доступ, это решит проблему. Но иногда, что-то может идти не по плану. И весь исходный код приложения станет открыт. Наверное, вы и сами понимаете, что это нехорошо.

Давайте, в папке проекта создадим две директории: `public` и `src` и поместим `index.php` в `public`. Помните, что мы не хотим ничего расскрывать, поэтому вставьте следующий код в файл `index.php`:

[source,php]
----
<?php declare(strict_types = 1); 

require __DIR__ . '/../src/Bootstrap.php';
----

`__DIR__` это https://www.php.net/manual/ru/language.constants.predefined.php[магическая константа], которая содержит путь к текущему каталогу. Используя данную константу, можно убедиться в том, что `require` всегда возвращает относительный путь к файлу, в противном случае, если `index.php` будет вызван из другой папки, то файл не найдется. Подробнее о работе `__DIR__` и других магических константах читайте в https://www.php.net/manual/ru/language.constants.magic.php[документации].


`declare(strict_types = 1);` устанавливает для текущего файла https://www.php.net/manual/ru/functions.arguments.php#functions.arguments.type-declaration.strict[строгую типизацию]. В этом руководстве мы будем применять строгую типизацию во всем проекте. Использование строгой типизации означает, что вы не можете просто передать целое число в качестве параметра методу, которому требуется строка. Если вы не используете строгий режим, он будет автоматически приведен к требуемому типу. В строгом режиме он выдаст исключение, если был применен неправильный тип. 

`Bootstrap.php`, файл, который связывает приложение вместе. Мы дойдем до него в ближайшее время.

Остальная часть `public` будет содержать файлы ресурсов (такие как файлы JavaScript и css). 

Теперь перейдем в папку `src` и создадим новый `Bootstrap.php` файл со следующим содержимым: 

[source,php]
----
<?php declare(strict_types = 1);

echo 'Hello World!';
----

Теперь давайте посмотрим, все ли настроено правильно. Откройте консоль и перейдите к папку `public`. Там введите php -S localhost:8000 и нажмите `Enter`. Это запустит встроенный веб-сервер, и вы сможете получить доступ к своей странице в браузере по ссылке:

[source,txt]
---- 
http://localhost:8000` 
----
Вы должны увидеть сообщение `«hello world»`.

Если есть ошибка, вернитесь и попробуйте исправить. Если вы видите только пустую страницу, проверьте окно консоли, в котором работает сервер, на наличие ошибок. 

Сейчас самое время зафиксировать процесс. Если вы еще не используете Git, настройте репозиторий прямо сейчас. Это не учебник по Git, поэтому я не буду вдаваться в подробности. Но использование контроля версий должно войти в привычку, даже если это просто учебный проект, подобный этому.

Некоторые редакторы и IDE помещают свои собственные файлы в папки проекта. Если это так, создайте файл `.gitignore` в корне вашего проекта и исключите файлы/каталоги. Ниже приведен пример для PHPStorm: 

[source,php]
---- 
.idea/
----



link:02-composer.adoc[Composer >>].