= Composer
:toc:

link:01-front-controller.adoc[<< Front controller].

https://getcomposer.org/[Composer] - это менеджер зависимостей (пакетов) для PHP.

Тот факт, что вы не используете фреймворк, не означает, что вам придется изобретать велосипед каждый раз, когда вы хотите что-то сделать. С помощью`Composer` вы можете установить сторонние библиотеки для разработки приложения.

Если у вас еще не установлен `Composer`, перейдите на веб-сайт и https://getcomposer.org/doc/00-intro.md[установите] его. Вы можете найти пакеты Composer для своего проекта на https://packagist.org/[`Packagist`].

Создайте новый файл в корневой папке проекта с именем `composer.json`. Это файл конфигурации `Composer`, который будет использоваться для настройки проекта и его зависимостей. Это должен быть валидный `JSON`, иначе `Composer` не работает.

Добавьте в файл `composer.json` следующее содержимое: 

[source,php]
----
{
    "name": "Project name",
    "description": "Your project description",
    "keywords": ["Your keyword", "Another keyword"],
    "license": "MIT",
    "authors": [
        {
            "name": "Your Name",
            "email": "your@email.com",
            "role": "Creator / Main Developer"
        }
    ],
    "require": {
        "php": ">=7.0.0"
    },
    "autoload": {
        "psr-4": {
            "Example\\": "src/"
        }
    }
}
----


В части `autoload` вы можете видеть, что я использую namespace (пространство имен) `Example` для проекта. Вы можете использовать все, что подходит для вашего проекта, но с этого момента далее в проекте я стану использовать namespace Example в своих примерах. 

Откройте новое окно консоли и перейдите в корневую папку проекта. В терминале наберите `composer update`.

`Composer` создаст файл `composer.lock`, который блокирует ваши зависимости и фиксирует их версии. Хранение файла `composer.lock` в репозитории является хорошей практикой. Это позволяет всем разработчикам использовать одинаковые версии пакетов на всех машинах и решает проблему "работает только на моей машине".

При этом вам не надо помещать  исходный код ваших зависимостей в свой репозиторий git . Итак, давайте добавим правило в файл ` .gitignore`:

[source,php]
----
vendor/
----

Теперь у нас имеется каркас приложения, который мы можем развивать дальше, для того, чтобы написать своё приложение.


link:03-error-handler.adoc[Error Handler >>].