
= Error Handler (Обработчик ошибок)
:toc:

link:02-composer.adoc[<< Composer].

Обработчик ошибок позволяет перехватывать исключения и выводить исчерпывающую информацию об ошибках на экран. Пакет, который мы установим, как раз занимается этим.

Мне нравится https://github.com/filp/whoops[filp/whoops], поэтому я покажу как его установить для проекта. Если вы предпочитаете другой пакет, не стесняйтесь подключите тот, который вам больше нравится. В этом прелесть программирования без фреймворка, у вас есть полный контроль над проектом. Альтернативный пакет: https://github.com/JosephLenton/PHP-Error[PHP-Error].

Чтобы установить новый пакет, откройте `composer.json` и добавьте пакет в секцию `require`. Это должно выглядеть так: 


[source,php]
----
"require": {
    "php": ">=7.0.0",
    "filp/whoops": "~2.1"
},
----

Запустите в консоли `composer update`. 

Так как PHP не знает, где найти файлы классов, пакет не будет работать. Для того, чтобы подключаемые библиотеки работали, нам понадобится https://www.php-fig.org/psr/psr-4/[автозагрузчик]. `Composer` уже позаботится об этом, так что  нужно только добавить `require __DIR__ . '/../vendor/autoload.php';` в `Bootstrap.php`.

*Важно:* Никогда не показывайте ошибки в `production` среде. Трассировка стека или даже простое сообщение об ошибке может помочь кому-то получить доступ к системе. Вместо этого всегда показывайте удобную для пользователя страницу с ошибкой и отправляйте электронное письмо самому себе, записывайте в журнал (log) или что-то подобное. 

Однако для разработки (`production`) - это не имеет смысла. Нам просто нужна красивая страница с выводом ошибки. Мы можем настроить в коде переключение среды разработки. 

`Bootstrap.php` теперь должен выглядеть примерно так: 

[source,php]
----
<?php declare(strict_types = 1);

namespace Example;

require __DIR__ . '/../vendor/autoload.php';

error_reporting(E_ALL);

$environment = 'development';

/**
* Register the error handler
*/
$whoops = new \Whoops\Run;
if ($environment !== 'production') {
    $whoops->pushHandler(new \Whoops\Handler\PrettyPageHandler);
} else {
    $whoops->pushHandler(function($e){
        echo 'Todo: Friendly error page and send an email to the developer';
    });
}
$whoops->register();

throw new \Exception;
----

Теперь вы должны увидеть страницу ошибки с выделенной строкой. Если это не так, то вернитесь и отлаживайте, пока не заработает. Если всё получилось, самое время зафиксировать изменения.  

link:04-http.adoc[HTTP >>].