
= HTTP
:toc:

link:03-error-handler.adoc[<< Error Handler (Обработчик ошибок)].

В PHP уже есть встроенный механизм для работы с HTTP. Например, есть https://www.php.net/manual/ru/language.variables.superglobals.php[суперглобальные переменные], которые содержат информацию о запросе. Используя эти переменные, надо понимать, что они хороши для небольшого скрипта. Но если нам надо писать чистый и поддерживаемый https://ru.wikipedia.org/wiki/SOLID_(%D0%BE%D0%B1%D1%8A%D0%B5%D0%BA%D1%82%D0%BD%D0%BE-%D0%BE%D1%80%D0%B8%D0%B5%D0%BD%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D0%BE%D0%B5_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)[SOLID] код, который будет требовать дальнейшей поддержки и развития, то нам понадобится класс с хорошим объектно-ориентированным интерфейсом.

Опять же, вам не нужно изобретать велосипед, можно использовать уже готовую библиотеку.. Я решил написать свой собственный  https://github.com/PatrickLouys/http[HTTP-компонент], потому что мне не нравились существующие, но вам не обязательно делать тоже самое.

Некоторые альтернативы: https://github.com/symfony/http-foundation[Symfony HttpFoundation], https://github.com/nette/http[HTTP Component], https://github.com/auraphp/Aura.Web[Aura Web], https://github.com/sabre-io/http[sabre/http].

В этом уроке я буду использовать свой собственный компонент HTTP, но вы можете использовать любой другой пакет. Вам нужно будет настроить код из учебника самостоятельно.

Отредактируйте `composer.json`, чтобы добавить новый компонент, а затем запустите `composer update`: 

[source,php]
----
"require": {
    "php": ">=7.0.0",
    "filp/whoops": "~2.1",
    "patricklouys/http": "~1.4"
  },
----

Теперь добавьте следующее ниже кода обработчика ошибок в `Bootstrap.php`(и не забудьте удалить исключение): 

[source,php]
----
$request = new \Http\HttpRequest($_GET, $_POST, $_COOKIE, $_FILES, $_SERVER);
$response = new \Http\HttpResponse;
----

Это установка Request, а также Response объектов, которые используются для получения данных запроса и отправки ответа обратно в браузер.

Чтобы отправить что-то в браузер, добавим следующий фрагмент в конце `Bootstrap.php` файла: 

[source,php]
----
foreach ($response->getHeaders() as $header) {
    header($header, false);
}

echo $response->getContent();
----

C помощью кода выше, данные ответа отправятся в браузер. Если этого не сделать, ничего не произойдет, т.к. Response объект только хранит данные. Большинство других компонентов HTTP по-разному делают обработку ответа, поэтому имейте в виду, если вы используете другой компонент.

Второй параметр `header()` имеет значение `false`, поскольку в противном случае существующие заголовки были бы перезаписаны.

Прямо сейчас он просто отправляет пустой ответ обратно в браузер с кодом состояния `200`; чтобы изменить это, добавьте следующий код между фрагментами кода сверху (прямо перед foreach):

[source,php]
----
$content = '<h1>Hello World</h1>';
$response->setContent($content);
----

Если вы хотите использовать ошибку `404`, используйте следующий код:

[source,php]
----
$response->setContent('404 - Page not found');
$response->setStatusCode(404);
----

Помните, что `Response` только хранит данные, поэтому, если вы установите несколько кодов состояния перед отправкой ответа, будет применен только последний из них.

В последующих частях я покажу вам, как использовать различные функции компонентов. А пока не стесняйтесь читать документацию или https://github.com/PatrickLouys/http[исходный код], если хотите узнать, как работает библиотека. 

link:05-router.adoc[Router (Маршрутизатор) >>].