
= Dispatching to a Class (Разделение задач)
:toc:

link:05-router.adoc[<< Router (Маршрутизатор)].

В этом руководстве мы не будем реализовывать http://martinfowler.com/eaaCatalog/modelViewController.html[MVC (Model-View-Controller)].

MVC в любом случае не может быть полностью реализовано в PHP, по крайней мере, не так, как это было задумано изначально. Если вы хотите узнать больше об этом, прочтите http://blog.ircmaxell.com/2014/11/a-beginners-guide-to-mvc-for-web.html[Руководство для начинающих по MVC] и последующие сообщения в блоге.

Так что забудьте о MVC и вместо этого давайте обратимся к https://ru.wikipedia.org/wiki/%D0%A0%D0%B0%D0%B7%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_%D0%BE%D1%82%D0%B2%D0%B5%D1%82%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D0%BE%D1%81%D1%82%D0%B8[разделению задач].

Нам нужно дать имя классам, которые будут обрабатывать запросы. Для этого урока я буду использовать название `Controllers (Контроллеры)`, потому что людям, работающим в рамках фреймворка, будет это знакомо. Еще одно название этим классам - `Handlers (Обработчики)`.

Создайте новую папку внутри `src/` с именем `Controllers`. В этой папке мы разместим все классы контроллеров. Там создайте файл `Homepage.php` со следующим кодом:

[source,php]
----
<?php declare(strict_types = 1);

namespace Example\Controllers;

class Homepage
{
    public function show()
    {
        echo 'Hello World';
    }
}
----

Автозагрузчик будет работать только в том случае, если пространство имен класса совпадает с путем к файлу, а имя файла соответсвует имени класса. В начале я определил `Example` как корневое пространство имен, которое принадлежит директории `src/`.

Теперь давайте изменим маршрут `/hello-world`. Напишите в файле `Routes.php` следующий код:

[source,php]
----
return [
    ['GET', '/', ['Example\Controllers\Homepage', 'show']],
];
----

Вместо функции, теперь передается массив. Первое значение - это имя класса с полным пространством имен, второе - имя метода, который будет вызываться для обработки запроса.

Нам также придется провести небольшой рефакторинг кода в `Bootstrap.php`:

[source,php]
----
case \FastRoute\Dispatcher::FOUND:
    $className = $routeInfo[1][0];
    $method = $routeInfo[1][1];
    $vars = $routeInfo[2];
    
    $class = new $className;
    $class->$method($vars);
    break;

----

Таким образом, вместо того, чтобы просто вызывать метод, мы создаем объект контроллера и вызываем обработчик из этого экземпляра класса.

Теперь, если вы перейдете по ссылке `http://localhost:8000/` все должно работать. Если нет, вернитесь назад и выполните отладку. И, конечно же, не забудьте зафиксировать свои изменения.

link:07-inversion-of-control.adoc[Inversion of Control (Инверсия управления)>>].