
= Inversion of Controls (Инверсия управления)
:toc:

link:06-dispatching-to-a-class.adoc[<< Dispatching to a Class (Разделение задач)].

В прошлом уроке, настроив класс контроллера, мы сгенировали выходные данные с помощью команды `echo`. Но давайте не будем забывать, что у нас есть хорошая объектно-ориентированная абстракция HTTP.  Правда прямо сейчас, у нас нет доступа к классам ответа и запроса из нашего контроллера.

Разумный вариант - использовать https://ru.wikipedia.org/wiki/%D0%98%D0%BD%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D1%8F_%D1%83%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F[инверсию управления]. 

Это означает, что вместо того, чтобы возлагать на класс ответственность за создание нужного ему объекта, мы просто запрашиваем его. Это реализуется с помощью https://ru.wikipedia.org/wiki/%D0%92%D0%BD%D0%B5%D0%B4%D1%80%D0%B5%D0%BD%D0%B8%D0%B5_%D0%B7%D0%B0%D0%B2%D0%B8%D1%81%D0%B8%D0%BC%D0%BE%D1%81%D1%82%D0%B8[внедрения зависимостей].

Если сейчас сказанное выше, звучит много сложно, не волнуйтесь. Просто следуйте руководству, и вскоре вы поймете, что такой подход прост в реализации.

Измените контроллер `Homepage` на следующий код: 

[source,php]
----
<?php declare(strict_types = 1);

namespace Example\Controllers;

use Http\Response;

class Homepage
{
    private $response;

    public function __construct(Response $response)
    {
        $this->response = $response;
    }

    public function show()
    {
        $this->response->setContent('Hello World');
    }
}

----

Обратите внимание, что мы http://php.net/manual/ru/language.namespaces.importing.php[импортируем] `Http\Response` в верхней части файла. Это означает, что всякий раз, когда вы используете `Response` внутри этого файла, он будет преобразован в полное имя класса.

В конструкторе мы явно указываем тип аргумента как `Http\Response`. В данном случае `Http\Response` - это интерфейс, и следовательно, любой класс, который реализовывает данный интерфейс может быть внедрен в наш контроллер.

Более подробно об http://fi2.php.net/manual/ru/functions.arguments.php#functions.arguments.type-declaration[объявлении типов] и http://fi2.php.net/manual/ru/language.oop5.interfaces.php[интерфейсах].

Так как мы еще ничего не внедрили, код будет генерировать ошибку. Так что давайте исправим это в файле `Bootstrap.php`, при создании экземпляра контроллера, передадим объект ответа в аргумент конструктора:

[source,php]
----
$class = new $className($response);
$class->$method($vars);
----

Класс `Http\HttpResponse` реализует интерфейс `Http\Response`, поэтому он выполняет контракт и значит мы можем использовать его в данном контроллере.

Теперь код должен работать. Но в этом случае абсолютно все контроллеры будут принимать одни и теже объекты. Мы это исправим в следующем разделе.

link:08-dependency-injector.adoc[Dependency Injector (Инъектор зависимостей)>>].