
= Dynamic pages (Динамические страницы)
:toc:

link:ink:09-templating.adoc[<< Templating (Шаблонизация)].

Пока у нас есть только статическая страница. Простой пример 'hello world' мало интересен, поэтому давайте пойдем дальше. Добавим в приложение некоторый функционал.

Для начала включим в наше приложение динамические страницы, созданные из https://en.wikipedia.org/wiki/Markdown[markdown] файлов.

Создадим `Page` контроллер со следующим содержимым: 

[source,php]
----
<?php declare(strict_types = 1);

namespace Example\Controllers;

class Page
{
    public function show($params)
    {
        var_dump($params);
    }
}
----

Не забудьте также добавить новый маршрут:

[source,php]
----
['GET', '/{slug}', ['Example\Controllers\Page', 'show']],
----

Теперь попробуйте окрыть в браузере несколько URL-адресов, например `http://localhost:8000/test`, а также `http://localhost:8000/hello`. Как видите, `Page` контроллер вызывается каждый раз, и массив `$params` получает `slug` (уникальная строка идентификатор) страницы.

Итак, давайте создадим несколько страниц. Мы пока не будем использовать базу данных, поэтому сформируйте новую папку `pages` в корневой папке проекта. Добавьте несколько файлов с расширениями файлов `.md`, например `page-one.md`. В файлах напишите любой текст:

[source,php]
----
This is a page.
----

Теперь мы должны написать код для чтения нужного файла и отображения содержимого. Может показаться заманчивым просто поместить весь этот код в `Page` контроллер. Но помните о https://en.wikipedia.org/wiki/Separation_of_concerns[Разделении интересов]. Есть большая вероятность, что нам нужно будет читать страницы и в других местах приложения (например, в админке).

Итак, давайте вынесем эту функциональность в отдельный класс. Есть большая вероятность, что позже мы сможем переключиться с файлов на базу данных, поэтому давайте снова воспользуемся интерфейсом, чтобы отделить нашу программу чтения страниц от фактической реализации.

В папке `src` создайте новую папку `Page`. Туда поместим все классы, связанные со страницей. Добавьте в эту папку новый файл с именем `PageReader.php` с таким содержимым: 

[source,php]
----
<?php declare(strict_types = 1);

namespace Example\Page;

interface PageReader
{
    public function readBySlug(string $slug) : string;
}
----

Для реализации создайте файл `FilePageReader.php`: 

[source,php]
----
<?php declare(strict_types = 1);

namespace Example\Page;

use InvalidArgumentException;

class FilePageReader implements PageReader
{
    private $pageFolder;

    public function __construct(string $pageFolder)
    {
        $this->pageFolder = $pageFolder;
    }

    public function readBySlug(string $slug) : string
    {
        return 'I am a placeholder';
    }
}
----

Как видите, нам требуется путь к папке страницы в качестве аргумента конструктора. Это делает класс гибким, и если мы решим переместить файлы или написать модульные тесты для класса, мы можем легко изменить местоположение с помощью аргумента конструктора.

Вы также можете поместить код, связанный со страницей, в свой собственный пакет и повторно использовать его в разных приложениях.

Этого пока хватит. Создадим файл шаблона для наших страниц с именем `Page.html` в папке `templates`. И пока просто добавьте `{{ content }}`.

Внесите следующие изменения в файл `Dependencies.php`, чтобы приложение знало, какую реализацию внедрить для нового интерфейса. Также определяем `pageFolder`. 

[source,php]
----
$injector->define('Example\Page\FilePageReader', [
    ':pageFolder' => __DIR__ . '/../pages',
]);

$injector->alias('Example\Page\PageReader', 'Example\Page\FilePageReader');
$injector->share('Example\Page\FilePageReader');
----

Теперь вернитесь к `Page` контроллер и измените метод `show`: 

[source,php]
----
public function show($params)
{
    $slug = $params['slug'];
    $data['content'] = $this->pageReader->readBySlug($slug);
    $html = $this->renderer->render('Page', $data);
    $this->response->setContent($html);
}
----

Чтобы сделать эту работу, нам нужно будет воспользоваться `Response`, `Renderer` и `PageReader`. Я оставлю это вам в качестве упражнения. Используй в качестве примера `Homepage` контроллер. Не забывай про правильные пространства имен `use`.

У тебя все заработало?

Если нет, то вот как теперь должно выглядеть начало вашего контроллера: 

[source,php]
----
<?php declare(strict_types = 1);

namespace Example\Controllers;

use Http\Response;
use Example\Template\Renderer;
use Example\Page\PageReader;

class Page
{
    private $response;
    private $renderer;
    private $pageReader;

    public function __construct(
        Response $response,
        Renderer $renderer,
        PageReader $pageReader
    ) {
        $this->response = $response;
        $this->renderer = $renderer;
        $this->pageReader = $pageReader;
    }

    ...
}
----

Пока все хорошо, теперь давайте сделаем наш `FilePageReader`.

Нам нужно иметь возможность сообщить, что страница не найдена. Для этого мы можем создать собственное исключение, которое мы сможем перехватить позже. В папке `src/Page` создайте `InvalidPageException.php` с таким содержимым: 

[source,php]
----
<?php declare(strict_types = 1);

namespace Example\Page;

use Exception;

class InvalidPageException extends Exception
{
    public function __construct($slug, $code = 0, Exception $previous = null)
    {
        $message = "No page with the slug `$slug` was found";
        parent::__construct($message, $code, $previous);
    }
}
----

Затем в `FilePageReader` добавьте этот код в конец файла в метод `readBySlug`: 

[source,php]
----
$path = "$this->pageFolder/$slug.md";

if (!file_exists($path)) {
    throw new InvalidPageException($slug);
}

return file_get_contents($path);
----

Теперь, если вы перейдете на несуществующую страницу, вы должны увидеть ошибку `InvalidPageException`. Если файл существует, вы должны увидеть его содержимое.

Конечно, показывать пользователю исключение для недопустимого URL-адреса не имеет смысла. Итак, давайте поймаем исключение и вместо этого покажем ошибку со статусом кода `404`.

В `Page` контроллер исправим метод `show`: 

[source,php]
----
public function show($params)
{
    $slug = $params['slug'];

    try {
        $data['content'] = $this->pageReader->readBySlug($slug);
    } catch (InvalidPageException $e) {
        $this->response->setStatusCode(404);
        return $this->response->setContent('404 - Page not found');
    }
    
    $html = $this->renderer->render('Page', $data);
    $this->response->setContent($html);
}
----

Убедитесь, что вы используете пространства имен для `InvalidPageException` в верху файла.

Попробуйте несколько разных URL-адресов, чтобы убедиться, что все работает как надо. Если что-то не так, вернитесь и отлаживайте, пока не заработает.

И, как всегда, не забудьте зафиксировать изменения в Git. 

link:11-page-menu.adoc[Page menu (Меню страницы)>>].
